name: Build & Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-run-linter:
    name: Build & run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        working-directory: ./mobile-app
        run: npm install

      - name: Build proj
        working-directory: ./mobile-app
        run: npm run build

      - name: Run linter
        working-directory: ./mobile-app
        run: npm run lint
