name: Build & Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-run-linter:
    name: Build & run linter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `mobile-app/package.json`
      - name: Install Node.js dependencies for mobile app
        working-directory: ./mobile-app
        run: npm install

      - name: Build mobile app
        working-directory: ./mobile-app
        run: npm run build

      - name: Run linter on mobile app
        working-directory: ./mobile-app
        run: npm run lint

      # ESLint and Prettier must be in `cmp/package.json`
      - name: Install Node.js dependencies for cmp
        working-directory: ./cmp
        run: npm install

      - name: Run formatter on cmp
        working-directory: ./cmp
        run: npm run format

      - name: Run linter on cmp
        working-directory: ./cmp
        run: npm run lint
